FROM ubuntu:14.04
MAINTAINER leandrosouza <leandrocsfrb@gmail.com> 

RUN locale-gen en_US.UTF-8 
RUN apt-get update
RUN apt-get install -q -y libfontconfig1 libgconf-2-4 libxi6 libxrender1 libxtst6


#/usr/local/MATLAB/R2015b/bin/matlab
